### ISSUE TITLE
ipfs 0.8.0 not supported

### ISSUE THREAD

**Issue by jcea** [SupraSummus/ipfs-api-mount#43]
I get this traceback:

```
jcea@jcea:/tmp/ram$ ipfs-api-mount-whole --timeout 30 /tmp/ram/ipfs
Traceback (most recent call last):
  File "/usr/local/bin/ipfs-api-mount-whole", line 7, in <module>
    IPFSApiMountWholeCommand().run()
  File "/usr/local/lib/python3.9/site-packages/ipfs_api_mount/commands.py", line 63, in run
    with ipfshttpclient.connect(
  File "/usr/local/lib/python3.9/site-packages/ipfshttpclient/client/__init__.py", line 119, in connect
    assert_version(client.apply_workarounds()["Version"])
  File "/usr/local/lib/python3.9/site-packages/ipfshttpclient/client/__init__.py", line 69, in assert_version
    raise exceptions.VersionMismatch(version, minimum, maximum)
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.8.0' (not in range: 0.4.23 ≤ … < 0.8.0)
```

**Comment by SupraSummus** [comment]
Yep, ipfshttpclient doesn't support goipfs v0.8.x.

**Comment by ThomasFreedman** [comment]
Any ETA when it will?

**Comment by SupraSummus** [comment]
I don't know any time bounds on this. However, there is some movement in py-ipfs-http-client repo. VersionMismatch error was changed into warning - https://github.com/ipfs-shipyard/py-ipfs-http-client/commit/724e7b264ea05fa811dca01a45a0694f713b43bd.

**Comment by ThomasFreedman** [comment]
It's been over a month, probably more like 2 since I attempted to use the python library. However when I did I patched the code to ignore the version mismatch and it appeared to the code is it was then wasn't compatible. I'm currently only using a few IPFS calls, so for now I'm interface I'm using is the command line with subprocess.popen.

I need an asynchronous interface so I can time out and or show progress so I used the nonblocking module to "poll" the stdout of the ipfs command process.
With slow Internet access and ipns requests I think it's important to provide as much feedback to the user as possible.

-------------------------------------------------------------------------
1) This private E-mail including but not limited to any / all attachment(s), are lawfully protected in any public jurisdiction subject to 1a.
2) Nunc pro tunc "Now for Then" (retroactive):  All Rights Reserved (Without Prejudice(2a)), Non Assumpsit(2b), and Without the United States(2c)1a) Electronic Communications Privacy Act, 18 U.S.C. § 2510-2521
2a) Without Prejudice UCC 1-308, UCC 1-306.6, in other words: All Rights Reserved
2b) Non Assumpsit "Did not undertake" (compulsory contracts)
2c) United States as defined by 26 USC § 77012c § 7701.9) Legalese: “The United States government is a foreign corporation with respect to a state" (20 C.J.S. Corporations §1785)
2c § 7701.10) Legalese: "include" in Latin: "expressio unius est exclusio alterius" or "to express or include one thing implies the exclusion of the other." Black's Law Dictionary (8th, 9th ed. 2009)

3) The color of the text above designates political jurisdiction: red-private non-statutory, flesh and blood, man / woman, blue-administrative, admiralty law, corporate jurisdiction. These are also pen ink colors and are significant on legal documents. Underlined text are links to further information.

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SupraSummus** [comment]
I've changed version of ipfshttpclient to 0.8.0a2, and the tests seem to pass. Pull request: #47
